In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statistics

##Assessing Data

In [2]:
data_df = pd.read_csv('https://raw.githubusercontent.com/andizabrina21/Alibaba-Stock-Prices-Analysis/refs/heads/main/Ali_Baba_Stock_Data.csv')
data_df

,Date,Adj Close,Close,High,Low,Open,Volume
0,2014-09-19,90.673950,93.889999,99.699997,89.949997,92.699997,271879400
1,2014-09-22,86.810966,89.889999,92.949997,89.500000,92.699997,66657800
2,2014-09-23,84.184128,87.169998,90.480003,86.620003,88.940002,39009800
3,2014-09-24,87.467667,90.570000,90.570000,87.220001,88.470001,32088000
4,2014-09-25,85.874191,88.919998,91.500000,88.500000,91.089996,28598000
...,...,...,...,...,...,...,...
2612,2025-02-07,103.510002,103.510002,107.510002,103.000000,104.459999,39538200
2613,2025-02-10,111.320000,111.320000,111.650002,106.699997,107.320000,42429400
2614,2025-02-11,112.779999,112.779999,115.540001,111.000000,113.959999,55001300
2615,2025-02-12,118.330002,118.330002,119.809998,114.964996,115.820000,44024700
2616,2025-02-13,119.540001,119.540001,119.570000,114.760002,115.330002,33191808

In [3]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2617 entries, 0 to 2616
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2617 non-null   object
 1   Adj Close  2617 non-null   float64
 2   Close      2617 non-null   float64
 3   High       2617 non-null   float64
 4   Low        2617 non-null   float64
 5   Open       2617 non-null   float64
 6   Volume     2617 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 143.2+ KB

date harus bertipe data datetime

In [4]:
data_df.isna().sum()

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [5]:
print("Jumlah duplikasi: ", data_df.duplicated().sum())

Jumlah duplikasi:  0

##Cleaning Data

In [6]:
data_df["Date"] = pd.to_datetime(data_df["Date"], errors="coerce")
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2617 entries, 0 to 2616
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2617 non-null   datetime64[ns]
 1   Adj Close  2617 non-null   float64
 2   Close      2617 non-null   float64
 3   High       2617 non-null   float64
 4   Low        2617 non-null   float64
 5   Open       2617 non-null   float64
 6   Volume     2617 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 143.2 KB

##Exploratory Data Analysis

###Analisis Deskriptif

In [7]:
data_df.describe()

,Date,Adj Close,Close,High,Low,Open,Volume
count,2617,2617.000000,2617.000000,2617.000000,2617.000000,2617.000000,2.617000e+03
mean,2019-11-30 14:35:26.709973248,130.763001,135.153905,136.919684,133.360942,135.248746,1.899231e+07
min,2014-09-19 00:00:00,55.424198,57.389999,58.650002,57.200001,57.299999,3.775300e+06
25%,2017-04-26 00:00:00,82.445793,84.849998,85.699997,84.000000,85.000000,1.186070e+07
50%,2019-11-29 00:00:00,105.469185,108.989998,110.650002,107.260002,108.500000,1.600840e+07
75%,2022-07-07 00:00:00,173.061798,179.199997,181.389999,177.000000,179.369995,2.172430e+07
max,2025-02-13 00:00:00,306.276886,317.140015,319.320007,308.910004,313.500000,2.718794e+08
std,NaN,56.741744,58.951556,59.579593,58.244218,59.037467,1.291504e+07

###EDA

In [8]:
data_df.agg({
    "Close": "sum",
    "High": "sum",
    "Low": "sum",
    "Volume": "mean"
})

Close     3.536978e+05
High      3.583188e+05
Low       3.490056e+05
Volume    1.899231e+07
dtype: float64

In [9]:
# Hitung Moving Averages
data_df["MA_50"] = data_df["Close"].rolling(window=50, min_periods=1).mean()
data_df["MA_200"] = data_df["Close"].rolling(window=200, min_periods=1).mean()

data_df[["Date", "Close", "MA_50", "MA_200"]]

           Date       Close      MA_50     MA_200
0    2014-09-19   93.889999  93.889999  93.889999
1    2014-09-22   89.889999  91.889999  91.889999
2    2014-09-23   87.169998  90.316666  90.316666
3    2014-09-24   90.570000  90.379999  90.379999
4    2014-09-25   88.919998  90.087999  90.087999
...         ...         ...        ...        ...
2612 2025-02-07  103.510002  88.149000  86.097750
2613 2025-02-10  111.320000  88.663800  86.291800
2614 2025-02-11  112.779999  89.215800  86.482550
2615 2025-02-12  118.330002  89.850600  86.698650
2616 2025-02-13  119.540001  90.494000  86.918600

[2617 rows x 4 columns]

In [10]:
ohlc = data_df.set_index("Date").resample("M").agg({
    "Open": "first",
    "High": "max",
    "Low": "min",
    "Close": "last"
})
ohlc

/tmp/ipykernel_17936/1987295677.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ohlc = data_df.set_index("Date").resample("M").agg({

                  Open        High         Low       Close
Date
2014-09-30   92.699997   99.699997   86.620003   88.849998
2014-10-31   88.699997  100.669998   82.809998   98.599998
2014-11-30   99.669998  120.000000   99.050003  111.639999
2014-12-31  110.019997  111.680000  101.199997  103.940002
2015-01-31  104.239998  105.339996   87.360001   89.080002
...                ...         ...         ...         ...
2024-10-31  106.419998  117.820000   95.519997   97.980003
2024-11-30   98.220001  101.099998   82.635002   87.370003
2024-12-31   86.940002   94.120003   81.699997   84.790001
2025-01-31   84.389999  103.665001   80.059998   98.839996
2025-02-28   96.504997  119.809998   96.070000  119.540001

[126 rows x 4 columns]

###Market Dynamics

In [11]:
#Daily Return
data_df['Daily Return'] = data_df['Close'].pct_change()
data_df['Daily Return']

0            NaN
1      -0.042603
2      -0.030259
3       0.039004
4      -0.018218
          ...
2612    0.031182
2613    0.075452
2614    0.013115
2615    0.049211
2616    0.010226
Name: Daily Return, Length: 2617, dtype: float64

In [12]:
# Volality
data_df["Volatility"] = data_df["Daily Return"].rolling(window=30).std()
data_df["Volatility"]

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
          ...
2612    0.024118
2613    0.027170
2614    0.027174
2615    0.027807
2616    0.027487
Name: Volatility, Length: 2617, dtype: float64

In [13]:
data_df.set_index("Date").resample("M").agg({
    "Volume": "mean"
})

/tmp/ipykernel_17936/1184934194.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  data_df.set_index("Date").resample("M").agg({

                  Volume
Date
2014-09-30  6.328680e+07
2014-10-31  1.921865e+07
2014-11-30  4.070625e+07
2014-12-31  1.615376e+07
2015-01-31  1.898510e+07
...                  ...
2024-10-31  2.271240e+07
2024-11-30  1.588884e+07
2024-12-31  1.350285e+07
2025-01-31  2.013548e+07
2025-02-28  3.368203e+07

[126 rows x 1 columns]

In [14]:
print(data_df.columns)

Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume', 'MA_50',
       'MA_200', 'Daily Return', 'Volatility'],
      dtype='object')

In [15]:
data_df.to_csv("alibaba_stock_clean.csv", index=False)